---
title: "KNN"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

__*k*-NN Using Riding Mowers Data__  
```{r loadpackages, warning=FALSE, message=FALSE}
pacman::p_load(caret, data.table, ggplot2, FNN)
knitr::opts_chunk$set(echo = FALSE, fig.width=12, fig.height=6, fig.path = 'Figs/')
theme_set(theme_classic())
options(digits = 3)
```


```{r readData}

mower.df <- read.csv("RidingMowers.csv")

  ### Partitioning data
set.seed(111)
train.index <- sample(row.names(mower.df), 0.7*dim(mower.df)[1])  
valid.index <- setdiff(row.names(mower.df), train.index)  
train.df <- mower.df[train.index, ]
valid.df <- mower.df[valid.index, ]

  ### New household with income and lot_size
new.df <- data.frame(Income = 60, Lot_Size = 20)

  ### Scatterplot of data
riding.plot1 <- ggplot(train.df) +
  geom_point(aes(Income, Lot_Size, color = Ownership), size = 3, shape = 19) +
  geom_point(aes(x=60, y=20), color="black", fill = "magenta1", size = 5, shape = 23) +
  scale_color_manual(values=c('red', 'blue')) +
  xlab("Income") +
  ylab("lotsize")

riding.plot1

plot(Lot_Size ~ Income, data=train.df, 
     pch=ifelse(train.df$Ownership=="Owner", 1, 3))
text(train.df$Income, train.df$Lot_Size, rownames(train.df), pos=4)
text(60, 20, "X")
legend("topright", c("owner", "non-owner", "newhousehold"), pch = c(1, 3, 4))

plot(Lot_Size ~ Income, data=mower.df, 
     pch=ifelse(mower.df$Ownership=="Owner", 1, 3))
text(mower.df$Income, mower.df$Lot_Size, rownames(mower.df), pos=4)
text(60, 20, "X")
legend("topright", c("owner", "non-owner", "newhousehold"), pch = c(1, 3, 4))

plot(Lot_Size ~ Income, data=valid.df, 
     pch=ifelse(valid.df$Ownership=="Owner", 1, 3))
text(valid.df$Income, valid.df$Lot_Size, rownames(valid.df), pos=4)
text(60, 20, "X")
legend("topright", c("owner", "non-owner", "newhousehold"), pch = c(1, 3, 4))

```

```{r knn}

# create copies
train.norm.df <- train.df
valid.norm.df <- valid.df
mower.norm.df <- mower.df
  
# Normalize data using preProcess() from CARET
set.seed(111)
norm.values <- preProcess(train.df[, 1:2], method=c("center", "scale"))
train.norm.df[, 1:2] <- predict(norm.values, train.df[, 1:2])
valid.norm.df[, 1:2] <- predict(norm.values, valid.df[, 1:2])
mower.norm.df[, 1:2] <- predict(norm.values, mower.df[, 1:2])
new.norm.df <- predict(norm.values, new.df)



# run knn using FNN package
nn <- knn(train = train.norm.df[, 1:2], test = new.norm.df, 
          cl = train.norm.df[, 3], k = 3)
  # Nearest-neighbor Index (ratio of observed distance divided by the expected distance)
row.names(train.norm.df)[attr(nn, "nn.index")]



# Chooose optimal K

  # Initialize a data frame with two columns: k and accuracy
accuracy.df <- data.frame(k = seq(1, 16, 1), accuracy = rep(0, 16))

  # compute knn for different k on validation
for(i in 1:16) {
  knn.pred <- knn(train.norm.df[, 1:2], valid.norm.df[, 1:2], 
                  cl = train.norm.df[, 3], k = i)
  accuracy.df[i, 2] <- confusionMatrix(knn.pred, valid.norm.df[, 3])$overall[1] 
}
accuracy.df


  # Re-run KNN with all observations 
    # using k = 4 (assuming it is "best")

knn.pred.new <- knn(mower.norm.df[, 1:2], new.norm.df, 
                    cl = mower.norm.df[, 3], k = 5)
row.names(mower.norm.df)[attr(knn.pred.new, "nn.index")]

```

