---
title: |
  | BUAN6356 
  | Clustering Notebook
date: "`r Sys.Date()`"
output:
  html_document:
    theme: cerulean
---

```{r loadpackages, warning=FALSE, message=FALSE}
pacman::p_load(tidyverse, ggrepel)
theme_set(theme_classic())
```

\  
__Utilities data__  
\  
```{r}
utilities.df <- read.csv("Utilities.csv")

# Variable descriptions:

# Fixed = fixed-charge covering ratio (income/debt) 
# RoR = rate of return on capital
# Cost = cost per kilowatt capacity in place
# Load = annual load factor
# Demand = peak kilowatthour demand growth from 1974 to 1975
# Sales = sales (kilowatthour use per year)
# Nuclear = percent nuclear
# Fuel Cost = total fuel costs (cents per kilowatthour)


dim(utilities.df)
names(utilities.df)
str(utilities.df)


# Scatterplot:  Sale v Fuel_Cost
g1 <- ggplot(utilities.df, aes(x=Fuel_Cost, y=Sales, label=Company)) + 
  geom_point(col = "blue", size = 3.5) +
  labs(x = "Fuel Cost", 
       title = "Relationship Between Fuel Cost and Sales",
       subtitle = "(for 22 Utility Companies)")

g1 + geom_label_repel(color = "dimgrey",
                      nudge_x = 0.1,
                      nudge_y = -0.2)

```

\  
__Calculate Distances__  
\  
```{r calcDistance}

# Set row names to the utilities column
row.names(utilities.df) <- utilities.df[,1]

# Remove the utility column (include only numeric variables in Cluster Analysis)
utilities.df <- utilities.df[,-1]

# Compute Euclidean distance
d <- dist(utilities.df, method = "euclidean")

# Normalize and calculate distances
utilities.df.norm <- sapply(utilities.df, scale)

# Add row names: utilities
row.names(utilities.df.norm) <- row.names(utilities.df) 

# Compute normalized distance based on variables Sales and FuelCost
d.norm <- dist(utilities.df.norm[,c(6,8)], method = "euclidean")
d.norm

# ALT: Compute normalized distance based on all 8 variables
d.norm <- dist(utilities.df.norm, method = "euclidean")
```

\  
__Hierarchical Clustering (Agglomerative Method)__  
\  
```{r}
  ## Generate Dendrogram using multiple methods  
hc1 <- hclust(d.norm, method = "single")
plot(hc1, hang = -1, main = "Single Linkage", col = "cornflowerblue") +
  abline(h=2.7, lty = 1, lwd = 1, col = "firebrick4")

hc2 <- hclust(d.norm, method = "complete")
plot(hc2, hang = -1, main = "Complete Linkage", col = "dodgerblue") +
  abline(h=3.8, lty = 1, lwd = 1, col = "firebrick4")

hc3 <- hclust(d.norm, method = "average")
plot(hc3, hang = -1, main = "Average Linkage", col = "deepskyblue") +
  abline(h= 3.5, lty = 1, lwd = 1, col = "firebrick4")

  ## Check memberships in above clusters
memb1 <- cutree(hc1, k = 6)
memb1

memb2 <- cutree(hc2, h = 3.8)
memb2

memb3 <- cutree(hc3, k = 6)
memb3

```


\  
__Validating clusters__  
\  
```{r heatmap}

library(RColorBrewer)
row.names(utilities.df.norm) <- paste(memb3, ": ", row.names(utilities.df), sep = "")

# Heatmap 
heatmap(as.matrix(utilities.df.norm), Colv = NA, hclustfun = hclust, col = brewer.pal(8, "PuBu"))

```


\  
__k-Means Clustering __  
\  
```{r}
set.seed(42)
km <- kmeans(utilities.df.norm, 6)

# Cluster size
km$size
# Cluster membership
km$cluster
# Within-cluster sum of squares
km$withinss
# Cluster centroids
km$centers
# Distance between cluster centroids
dist(km$centers)


# Generate a Profile Plot
  ## plot an empty scatter plot
plot(c(0), xaxt = 'n', ylab = "", xlab = "", type = "l", 
     ylim = c(min(km$centers), max(km$centers)), xlim = c(0, 8), bty = "n")
  ## label x-axes
axis(1, at = c(1:8), labels = names(utilities.df))
  ## plot centroids
for (i in c(1:6)) {
lines(km$centers[i,], lty = i, lwd = 2, col = ifelse(i %in% c(1, 3, 5),
                                                       "tomato", "olivedrab"))
}
  ## name clusters
text(x = 0.5, y = km$centers[, 1], labels = paste("Cluster", c(1:6)))


```




